FROM node:16.15-alpine3.14
RUN mkdir -p /opt/app
WORKDIR /opt/app
RUN adduser -S app
COPY . .
RUN npm ci
RUN npm install --save pm2
RUN chown -R app /opt/app
USER app
# COPY --chown=app:app . /opt/app
EXPOSE 5000

CMD [ "npm", "run", "pm2" ]